### ISSUE TITLE
Issue when deserializing a RFC2579DateTime value

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/dfdatetime#230]
When running plaso (latest from head at the time of the issue being sent out) against a set of files collected from a Mac OS X system an error occurs:

```
Traceback (most recent call last):
  File "<my_pyenv_path>/plaso_env/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20220816', 'log2timeline.py')
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/EGG-INFO/scripts/log2timeline.py", line 73, in Main
    tool.ExtractEventsFromSources()
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/cli/extraction_tool.py", line 730, in ExtractEventsFromSources
    processing_status = self._ProcessSources(session, storage_writer)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/cli/extraction_tool.py", line 587, in _ProcessSources
    storage_file_path=self._storage_file_path)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/extraction_engine.py", line 1017, in ProcessSources
    source_configurations, storage_writer, session_identifier)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/extraction_engine.py", line 591, in _ProcessSources
    self._ScheduleTasks(storage_writer, session_identifier)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/extraction_engine.py", line 705, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer, session_identifier)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/extraction_engine.py", line 476, in _MergeTaskStorage
    maximum_number_of_containers=self._maximum_number_of_containers)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/extraction_engine.py", line 388, in _MergeAttributeContainers
    container = merge_helper.GetAttributeContainer()
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/merge_helpers.py", line 64, in GetAttributeContainer
    container = next(self._generator)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/multi_process/merge_helpers.py", line 47, in _GetAttributeContainers
    container_type):
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/storage/sqlite/sqlite_file.py", line 401, in _GetAttributeContainersWithFilter
    container_type, column_names, row, 1)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/storage/sqlite/sqlite_file.py", line 332, in _CreatetAttributeContainerFromRow
    attribute_value = self._serializer.ReadSerialized(attribute_value)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/serializer/json_serializer.py", line 493, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/serializer/json_serializer.py", line 517, in ReadSerializedDict
    json_object = cls._ConvertJSONToValue(json_dict)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/plaso-20220816-py3.7.egg/plaso/serializer/json_serializer.py", line 294, in _ConvertJSONToValue
    return convert_function(json_dict)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/dfdatetime/serializer.py", line 34, in ConvertDictToDateTimeValues
    return cls.ConvertJSONToDateTimeValues(json_dict)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/dfdatetime/serializer.py", line 178, in ConvertJSONToDateTimeValues
    date_time = factory.Factory.NewDateTimeValues(class_name, **json_dict)
  File "<my_pyenv_path>/plaso_env/lib/python3.7/site-packages/dfdatetime/factory.py", line 46, in NewDateTimeValues
    return date_time_values_type(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'time_zone_offset'
```

This happens in the factory code, for `NewDateTimeValues` when the date class `RFC2579DateTime` is being called, the actual kwargs that is being sent by plaso does not confirm to the struct that `RFC2579DateTime` expects, which is
```
 16   struct {
 17       uin16_t year,
 18       uint8_t month,
 19       uint8_t day_of_month,
 20       uint8_t hours,
 21       uint8_t minutes,
 22       uint8_t seconds,
 23       uint8_t deciseconds,
 24       char direction_from_utc,
 25       uint8_t hours_from_utc,
 26       uint8_t minutes_from_utc
 27   }
```

But rather it has the form (the kwargs):

```
{'rfc2579_date_time_tuple': [2022, 1, 17, 12, 55, 51, 0], 'time_zone_offset': 0}
```

**Comment by kiddinn** [comment]
This will also happen within psort, when attempting to read the timeline data produced by plaso (hot patched dfdatetime to be able to run plaso on the dataset, but when attempting to import into Timesketch I run into this issue again, since that version is not hot patched)

```
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 490, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 293, in _ExportEvents
    for event in storage_reader.GetSortedEvents(time_range=time_slice_range):
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 405, in _GetAttributeContainersWithFilter
    container = self._CreatetAttributeContainerFromRow(
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 337, in _CreatetAttributeContainerFromRow
    attribute_value = self._serializer.ReadSerialized(attribute_value)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 493, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 517, in ReadSerializedDict
    json_object = cls._ConvertJSONToValue(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 294, in _ConvertJSONToValue
    return convert_function(json_dict)
  File "/usr/lib/python3/dist-packages/dfdatetime/serializer.py", line 34, in ConvertDictToDateTimeValues
    return cls.ConvertJSONToDateTimeValues(json_dict)
  File "/usr/lib/python3/dist-packages/dfdatetime/serializer.py", line 178, in ConvertJSONToDateTimeValues
    date_time = factory.Factory.NewDateTimeValues(class_name, **json_dict)
  File "/usr/lib/python3/dist-packages/dfdatetime/factory.py", line 46, in NewDateTimeValues
    return date_time_values_type(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'time_zone_offset'
```

**Comment by joachimmetz** [comment]
thx for the report, can you give the changes in the PR a try

**Comment by kiddinn** [comment]
works like a charm
