### ISSUE TITLE
AppVeyor Python 3.6 tests are failing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfdatetime#85]
From: https://ci.appveyor.com/project/joachimmetz/dfdatetime/build/289/job/dpv7r38vvuc1bgs3 

```
%PYTHON%\python.exe %PYTHON%\Scripts\pywin32_postinstall.py -install
Traceback (most recent call last):
  File "C:\Python36\Scripts\pywin32_postinstall.py", line 594, in <module>
    install()
  File "C:\Python36\Scripts\pywin32_postinstall.py", line 328, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "C:\Python36\Scripts\pywin32_postinstall.py", line 166, in LoadSystemModule
    mod = imp.load_dynamic(modname, filename)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
```

Online references indicate that DLL could require Microsoft Visual C++ 2010 Redistributable Package

**Comment by joachimmetz** [comment]
issue with pywin32, has been fixed
