### ISSUE TITLE
Fix failing dfvfs tests

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfdatetime#92]
dfvfs tests are failing with latest dfdatetime

```
======================================================================
FAIL: testGetStat (vfs.cpio_file_entry.CPIOFileEntryTest)
Tests the GetStat function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dfvfs/tests/vfs/cpio_file_entry.py", line 75, in testGetStat
    self.assertFalse(hasattr(stat_object, 'mtime_nano'))
AssertionError: True is not false

======================================================================
FAIL: testGetStat (vfs.gzip_file_entry.GZIPFileEntryTest)
Tests the GetStat function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dfvfs/tests/vfs/gzip_file_entry.py", line 70, in testGetStat
    self.assertFalse(hasattr(stat_object, 'mtime_nano'))
AssertionError: True is not false

======================================================================
FAIL: testGetStat (vfs.tar_file_entry.TARFileEntryTest)
Tests the GetStat function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dfvfs/tests/vfs/tar_file_entry.py", line 75, in testGetStat
    self.assertFalse(hasattr(stat_object, 'mtime_nano'))
AssertionError: True is not false
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfdatetime/commit/095d7d1efe81bdce8d5266d4465b330ac1186592
